version: '3'

services:
  app:
    container_name: qr-component
    build: .
    labels:
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.qr-component.rule=Host(`qr-component.mytestingenlocal.ml`)" # <== Your Domain Name for the https rule
      - "traefik.http.routers.qr-component.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
      - "traefik.http.routers.qr-component.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
      - "traefik.http.services.qr-component.loadbalancer.server.port=3000" # 3000 is the port we proxy to
      # no https
      - "traefik.http.routers.qr-component-http.rule=Host(`qr-component.mytestingenlocal.ml`)" # <== Your Domain Name goes here for the http rule
      - "traefik.http.routers.qr-component-http.entrypoints=web" # <== Defining the entrypoint for http, **ref: line 30
      - "traefik.http.routers.qr-component-http.middlewares=redirect@file" # <== This is a middleware to redirect to https
    networks:
      - web
    environment:
      - PORT: 3000

networks:
  web:
    external: true